apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  project: default  # Ajout du champ project
  destination:
    server: https://kubernetes.default.svc
    namespace: prod  # Utilisation du namespace 'prod' pour PROD
  source:
    repoURL: 'https://github.com/Oumaima-hr/app-repo'  # Ton dépôt Git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-prod.yaml  # Utilisation du fichier 'values-prod.yaml' pour PROD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
