apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod  # PROD namespace
  source:
    repoURL: 'https://github.com/Oumaima-hr/app-repo'  # Your GitHub repo URL
    targetRevision: HEAD
    path: k8s  # Use 'k8s' instead of 'helm'
    helm:
      valuesFile: values-prod.yaml  # Optional if you're using Helm in the future
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
